### ISSUE TITLE
Android Studio 3.3

### ISSUE THREAD

**Issue by fintecheand0** [openMF/android-client#1071]
**Summary:** 

While working on Android Studio 3.3 we got compilation errors related to annotations, although they are set as true .

**Steps to reproduce:** 

1. Import the project into Android Studio 3.3 with the annotations enabled.

**Expected behaviour:** 

APK must be built

**Observed behaviour:** 

Error while building the binary file

**Device and Android version:** 

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mifosng-android:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:61)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/0.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/1.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/2.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/3.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/4.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/5.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/6.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/7.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/8.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/9.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/10.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/11.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/12.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/13.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/14.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/15.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/16.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/17.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/18.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/19.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/20.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/21.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/22.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/23.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/24.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/25.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/26.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/27.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/28.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/29.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/30.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/31.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/32.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/33.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/34.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/35.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/36.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/37.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/38.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/39.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/40.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/41.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/42.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/43.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/44.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/45.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/46.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/47.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/48.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/49.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/50.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/51.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/52.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/53.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/54.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/55.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/56.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/57.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/58.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/59.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/60.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/61.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/62.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/63.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/64.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/65.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/66.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/67.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/68.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/69.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/70.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/71.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/72.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/73.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/74.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/75.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/76.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/77.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/78.jar
	at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 34 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/0.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/1.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/2.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/3.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/4.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/5.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/6.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/7.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/8.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/9.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/10.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/11.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/12.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/13.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/14.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/15.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/16.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/17.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/18.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/19.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/20.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/21.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/22.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/23.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/24.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/25.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/26.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/27.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/28.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/29.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/30.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/31.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/32.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/33.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/34.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/35.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/36.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/37.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/38.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/39.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/40.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/41.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/42.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/43.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/44.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/45.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/46.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/47.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/48.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/49.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/50.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/51.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/52.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/53.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/54.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/55.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/56.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/57.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/58.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/59.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/60.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/61.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/62.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/63.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/64.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/65.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/66.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/67.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/68.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/69.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/70.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/71.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/72.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/73.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/74.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/75.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/76.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/77.jar, /home/victor/git/android-client/mifosng-android/build/intermediates/transforms/dexBuilder/debug/78.jar
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	... 50 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:67)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	... 55 more
Caused by: com.android.tools.r8.utils.AbortException
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
	... 58 more

**Comment by tavishjain** [comment]
I have fixed this and #1079 in the PR #1083
